server:
   port: 8092

spring:
   application:
      name: typecontributor-service
   datasource:
      url: jdbc:mysql://localhost:3306/challenge_sintad
      username: root
      password: administrador