server:
   port: 8092
   servlet:
      context-path: /api

spring:
   application:
      name: typecontributor-service
   datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}