server:
   port: 8093
   servlet:
      context-path: /api
spring:
   application:
      name: auth-service
   datasource:
      url: jdbc:mysql://localhost:3306/challenge_sintad
      username: root
      password: administrador